name: movingpandas
channels:
  - conda-forge
  - default
dependencies:
  - python=3.7
  - bokeh
  - cartopy
  - cython
  - geopandas
  - geopy
  - geoviews
  - hvplot
  - jupyter
  - matplotlib
  - notebook
  - numpy
  - pandas
  - panel
  - proj
  - rasterio
  - scikit-learn
  - seaborn
  - movingpandas